name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: write
      discussions: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}


#    - name: Build
#      run: echo "${{github.event_name}} (${{ github.sha }})" > Release.txt
#    - name: Test
#      run: cat Release.txt
#    - name: Release
#      uses: softprops/action-gh-release@v1
#      with: 
#        body_path: Release.txt
#        generate_release_notes: true
#        token: ${{ secrets.GITHUB_TOKEN }}
#        draft: false
#        prerelease: false
#        files: |
#          Release.txt


    #        body_path: ${{ github.workspace }}/CHANGELOG.md
#
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#
#    - name: Create Release
#      uses: actions/create-release@v1
#      id: create_release
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        body_path: CHANGELOG.md
#        draft: false
#        prerelease: false
