name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  tests:
    uses: actions/checkout@v3 # Necessary to access local action
    uses: ./.github/workflows/CI.yml

  publish:
    name: publish
#    needs: [tests] # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
#      pull-requests: write
#      repository-projects: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: Create tag artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{github.ref_name}}
#        path: Release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        token: ${{ secrets.GITHUB_TOKEN }} 
        body_path: ${{ github.workspace }}/CHANGELOG.md
#
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#
#    - name: Create Release
#      uses: actions/create-release@v1
#      id: create_release
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        body_path: CHANGELOG.md
#        draft: false
#        prerelease: false
